name: Merge any release branch to uat
on:
  push:
    branches:
      - 'base'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@frontend

      - name: Merge staging -> base
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: base
          github_token: ${{ github.token }}
